title: PhD(c) Juan P. Carvajal
description: PhD candidate in astrophysics -- Observational | Dwarf Galaxies | Evolution
theme: jekyll-theme-minimal
# Optional:
# logo: /assets/img/headshot.jpg
# show_downloads: false
