title: PhD(c) Juan P. Carvajal
description: PhD candidate in astrophysics -- Observational, Spectroscopy, Photometry, Machine Learning  | Dwarf Galaxies | Evolution
theme: jekyll-theme-minimal

header_pages:
  - publications.md
  - outreach.md
  - featured.md